import NotFound from './404/404.js'
import Member from './member/member.js'
import Contacts from './contacts'
import Home from './home/home.js'
import About from './about/about.js'
import Loader from './loader/loader.js'
import Blog from './blog/blog.js'
import Services from './services/services.js'
import SuccessStories from './success_stories/success_stories.js'
import Support from './support/support.js'
import Shop from './shop/shop.js'
export { NotFound, Home, About, Services, SuccessStories, Support, Blog, Loader, Member, Contacts, Shop }
