import NotFound from './404/404.js'
import Member from './member'
import Contacts from './contacts'
import Home from './home/home.js'
import About from './about/about.js'
import Loader from './loader/loader.js'
import Blog from './blog/blog.js'
import Services from './services/services.js'
import SuccessStories from './success_stories/success_stories.js'
import Shop from './shop/shop.js'
import Girls from './girls/girls.js'
import Testimonials from './testimonials/testimonials.js'
import Faq from './faq/faq.js'
import Works from './works/works.js'
import Terms from './terms/terms.js'
export { NotFound, Home, About, Services, SuccessStories, Blog, Loader, Member, Contacts, Shop, Girls, Testimonials, Faq, Works, Terms }
