export default {
    'public': [
        {
            'path': '/',
            'component': 'Home'
        }, {
            'path': '/terms',
            'component': 'Terms'
        }, {
            'path': '/girls',
            'component': 'Home'
        }, {
            'path': '/success-stories',
            'component': 'SuccessStories'
        }, {
            'path': '/success-stories/:id',
            'component': 'SuccessStories'
        }, {
            'path': '/how-it-works',
            'component': 'Works'
        }, {
            'path': '/blogs',
            'component': 'Blog'
        }, {
            'path': '/blogs/:id',
            'component': 'Blog'
        }, {
            'path': '/testimonials',
            'component': 'Testimonials'
        }, {
            'path': '/about',
            'component': 'About'
        }, {
            'path': '/faq',
            'component': 'Faq'
        }, {
            'path': '/services',
            'component': 'Services'
        }, {
            'path': '*',
            'component': 'NotFound'
        }
    ],
    'client': [
        {
            'path': '/',
            'component': 'Home'
        }, {
            'path': '/about',
            'component': 'About'
        }, {
            'path': '/how-it-works',
            'component': 'Works'
        }, {
            'path': '/testimonials',
            'component': 'Testimonials'
        }, {
            'path': '/success-stories',
            'component': 'SuccessStories'
        }, {
            'path': '/success-stories/:id',
            'component': 'SuccessStories'
        }, {
            'path': '/profile/*',
            'component': 'Home'
        }, {
            'path': '/mail/*',
            'component': 'Home'
        }, {
            'path': '/girls',
            'component': 'Home'
        }, {
            'path': '/contacts/*',
            'component': 'Home'
        }, {
            'path': '/member/:id',
            'component': 'Member'
        }, {
            'path': '/shop',
            'component': 'Shop'
        }, {
            'path': '/shop/:prodId',
            'component': 'Shop'
        }, {
            'path': '/blogs',
            'component': 'Blog'
        }, {
            'path': '/blogs/:id',
            'component': 'Blog'
        }, {
            'path': '/services',
            'component': 'Services'
        }, {
            'path': '*',
            'component': 'NotFound'
        }
    ],
    'girl': [
        {
            'path': '/',
            'component': 'Home'
        }, {
            'path': '/profile/*',
            'component': 'Home'
        }, {
            'path': '/men',
            'component': 'Home'
        }, {
            'path': '/mail/*',
            'component': 'Home'
        }, {
            'path': '/contacts/*',
            'component': 'Home'
        }, {
            'path': '/member/:id',
            'component': 'Member'
        }, {
            'path': '/blogs',
            'component': 'Blog'
        }, {
            'path': '/blogs/:id',
            'component': 'Blog'
        }, {
            'path': '*',
            'component': 'NotFound'
        }
    ]
}